language: node_js
node_js:
  - node
# Cache previous installs to speed up builds
cache: yarn
# Force a new version of yarn to avoid build errors
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"